server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot-miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10
    pool:
      max-active: 1000
      max-idle: 500
      max-wait: 3
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
mybatis:
  type-aliases-package: com.lizhi.miaosha.domain
  mapper-locations: classpath:com/lizhi/miaosha/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000

pageCache:
  enbale: true

